### ISSUE TITLE
Ellipsoid Transform Singular Matrix Error

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-biop-tools#28]
@NicoKiaru 

I am sometimes (not sure yet when exactly) getting an error when trying to display this Ellipsoid Transform:
```
{
  "type": "Elliptical3DTransform",
  "ellipse_params": {
    "r1": 312.71591070585947,
    "r2": 305.59762752685947,
    "r3": 402.8561317741336,
    "rx": 2.372862129401533,
    "ry": 0.0,
    "rz": 0.0,
    "tx": 285.2807746430004,
    "ty": 301.9951720402016,
    "tz": -218.77616239495526
  }
}
```

```Exception in thread "PainterThread" Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Matrix is singular.
	at net.imglib2.realtransform.AffineTransform3D.invert(AffineTransform3D.java:362)
	at net.imglib2.realtransform.AffineTransform3D.set(AffineTransform3D.java:965)
	at bigwarp.BigWarpExporter.estimateAffineFromCorners(BigWarpExporter.java:697)
	at bdv.img.WarpedSource.estimateBoundingInterval(WarpedSource.java:144)
	at bdv.img.WarpedSource.getSource(WarpedSource.java:133)
	at bdv.viewer.render.ProjectorFactory.getTransformedSource(ProjectorFactory.java:281)
	at bdv.viewer.render.ProjectorFactory.createSingleSourceProjector(ProjectorFactory.java:213)
	at bdv.viewer.render.ProjectorFactory.createProjector(ProjectorFactory.java:170)
	at bdv.viewer.render.MultiResolutionRenderer.createProjector(MultiResolutionRenderer.java:628)
	at bdv.viewer.render.MultiResolutionRenderer.paintFullFrame(MultiResolutionRenderer.java:465)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:439)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:473)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:82)
java.lang.RuntimeException: Matrix is singular.
	at net.imglib2.realtransform.AffineTransform3D.invert(AffineTransform3D.java:362)
	at net.imglib2.realtransform.AffineTransform3D.set(AffineTransform3D.java:965)
	at bigwarp.BigWarpExporter.estimateAffineFromCorners(BigWarpExporter.java:697)
	at bdv.img.WarpedSource.estimateBoundingInterval(WarpedSource.java:144)
	at bdv.img.WarpedSource.getSource(WarpedSource.java:133)
	at bdv.viewer.overlay.MultiBoxOverlayRenderer.setViewerState(MultiBoxOverlayRenderer.java:163)
```

Do you know what this is about?

**Comment by NicoKiaru** [comment]
You can download the catch-singular matrix version of BigWarp from the ABBA update site or test the current SNAPSHOT version of BigWarp for the moment
