### ISSUE TITLE
Failed during installation of Warpy on Fiji

### ISSUE THREAD

**Issue by maxull** [BIOP/bigdataviewer-biop-tools#75]
Followed the installation guidelines on the warpy site.

Installed fresh FIJI on Apple M3 Pro running macOS Sequoia Version 15.0.1
- ImageJ version 2.14.0/1.54f
- Updated 
- Restarted Fiji
- Enabled PTBIOP update site
- Restarted Fiji
- Downloaded elastix and transformix: https://github.com/SuperElastix/elastix/releases/tag/5.0.1
- Ran the .groovy script to test elastix: https://gist.githubusercontent.com/NicoKiaru/b91f9f3f0069b765a49b5d4629a8b1c7/raw/0744676341b16ee4f37ed203130f0e0b761c08c8/TestRegister.groovy
- Gave the correct path to extension
- Registration test failed, with below error message:

```
Started TestRegister.groovy at Tue Nov 26 15:20:06 CET 2024
java.lang.IllegalArgumentException: No such input: splineGridSpacing
	at org.scijava.command.CommandModule.setInput(CommandModule.java:171)
	at org.scijava.module.DefaultModuleService.assignInputs(DefaultModuleService.java:475)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:239)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:208)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:197)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:182)
	at org.scijava.command.DefaultCommandService.run(DefaultCommandService.java:183)
	at org.scijava.command.DefaultCommandService.run(DefaultCommandService.java:168)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at TestRegister.run(TestRegister.groovy:26)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:331)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:161)
	at org.scijava.plugins.scripting.groovy.GroovyScriptLanguage$1.eval(GroovyScriptLanguage.java:97)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:173)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

Apparently the groovy script that is linked on the webpage doesnt work, because using this script from GitHub instead works: https://gist.github.com/NicoKiaru/b91f9f3f0069b765a49b5d4629a8b1c7

**Comment by NicoKiaru** [comment]
Thanks, indeed I modified the API without modifying the command everywhere. Thanks a lot, I'll try to fix this in the next few days

**Comment by NicoKiaru** [comment]
Let's say I talked in Mercurian days

**Comment by NicoKiaru** [comment]
Gist has been fixed:

https://gist.github.com/NicoKiaru/b91f9f3f0069b765a49b5d4629a8b1c7

But, even better, there's a Test Elatix plugin in the PTBIOP update site in Fiji:

![Image](https://github.com/user-attachments/assets/7d2f4066-d047-4171-9383-b7280b0f31f1)
